apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "fullname" .}}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
        - name: cpfrontend
          image: "{{ .Values.Frontend.Image.Repository }}:{{ .Values.Frontend.Image.Tag }}"
          imagePullPolicy: {{ .Values.Frontend.Image.PullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: API_URL
              value: {{ .Values.Frontend.Environment.API_URL }}
            - name: APP_PROTOCOL
              value: {{ .Values.Frontend.Protocol }}
            - name: APP_HOST
              value: "cpanel{{- if .Values.Frontend.Branch -}}-{{ .Values.Frontend.Branch }}{{- end -}}.{{ .Values.ServicesDomain }}"
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-client-secret
            - name: AUTH0_DOMAIN
              value: "{{ .Values.Frontend.Environment.AUTH0_DOMAIN }}"
            - name: AUTH0_CALLBACK_URL
              value: "https://cpanel{{- if .Values.Frontend.Branch -}}-{{ .Values.Frontend.Branch }}{{- end -}}.{{ .Values.ServicesDomain }}/callback"
            - name: AWS_LOGIN_URL
              value: "{{ .Values.Frontend.Environment.AWS_LOGIN_URL }}"
            - name: ENV
              value: "{{ .Values.Frontend.Environment.ENV }}"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: sentry-dsn
            - name: REDIS_HOST
              value: "{{ printf "%s-%s" .Release.Name "redis" | trunc 63 | trimSuffix "-" }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ printf "%s-%s" .Release.Name "redis" | trunc 63 | trimSuffix "-" }}"
                  key: redis-password
            - name: SERVICES_DOMAIN
              value: "{{ .Values.ServicesDomain }}"
            - name: TOOLS_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: tools-domain
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
