apiVersion: v1
appVersion: "1.0"
description: Deploys resources related to the [Prometheus-Operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) helm chart
name: prometheus-resources
version: 0.1.0
engine: gotpl
