appDomain: ""

# Auth0 client credentials for accessing the Auth0 Management API
auth0:
  authzAudience: ""
  authzUrl: ""
  clientId: ""
  clientSecret: ""
  domain: ""

aws:
  ecrAccessKeyId: ""
  ecrSecretAccessKey: ""
  region: "eu-west-1"
  nodesRoleArn: ""
  iamListRolesAccessKeyId: ""
  iamListRolesSecretAccessKey: ""
  lookupAccessKeyId: ""
  lookupSecretAccessKey: ""
  rolePutterAccessKeyId: ""
  rolePutterSecretAccessKey: ""
  parameterAccessKeyId: ""
  parameterSecretAccessKey: ""

concourse:
  # externalURL is the same value as for the concourse helm chart
  externalURL: ""
  password: ""
  team: main
  username: ""
  pipeline_name: "create-webapp-pipelines"
  target_team: ""
  target_username: ""
  target_password: ""

cookieSecret: ""

cpanelApi:
  password: ""
  url: ""
  user: ""

github:
  org: moj-analytical-services
  accessToken: ""
  webhookToken: ""

githubOrgResource:
  image: quay.io/mojanalytics/github-org-resource
  tag: v0.6.0

ipRanges:
  wifi102pf: ""
  dom1: ""
  quantum: ""
  mojDigitalWifiAndVpn: ""
  alanTuringInstitute: ""

kubernetes:
  apiUrl: ""
  caCert: ""
  token: ""
