# Delete pods after...
deleteFailedAfter: 10 # days
deletePendingAfter: 10 # days
deleteSucceededAfter: 3 # days

# Docker image
image: "bitnami/kubectl:1.14.1"

# Schedule when to run
#   min    hour   day    month (Sun-Sat)
# "(0-59) (0-23) (1-31) (1-12) (0-6)"
# See https://kubernetes.io/docs/user-guide/cron-jobs/#schedule
schedule: "0 5 * * *"
