apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "unidle_key" . }}
    unidle-key: {{ template "unidle_key" . }}
spec:
  sessionAffinity: ClientIP
  selector:
    app: "{{ .Chart.Name }}"
  ports:
  - port: 80
    targetPort: {{ .Values.authProxy.express.port }}
