apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-ingress.controller.fullname" . }}-nlb
  namespace: {{ .Release.Namespace }}
  annotations:
  # https://github.com/kubernetes/kubernetes/blob/10688257e63e4d778c499ba30cddbc8c6219abe9/pkg/cloudprovider/providers/aws/aws.go#L98
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  loadBalancerSourceRanges:
    - "0.0.0.0/0"
  externalTrafficPolicy: Local
  selector:
    app: {{ template "nginx-ingress.name" . }}
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  # https://github.com/kubernetes/kubernetes/issues/56703
  type: LoadBalancer
