ServicesDomain: ""
API:
  DeployOwnDatabase: false
  Branch: "master"
  Image:
    Repository: quay.io/mojanalytics/control-panel
    Tag: 0.1.0
    PullPolicy: IfNotPresent
  Environment:
    DEBUG: "False"
    ENABLE_K8S_RBAC: "False"
    ENV: ""
    IAM_ARN_BASE: ""
    K8S_WORKER_ROLE_NAME: ""
    LOGS_BUCKET_NAME: ""
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
    OIDC_DOMAIN: ""
    OIDC_AUTH_EXTENSION_URL: ""
    SAML_PROVIDER: ""
    SENTRY_DSN: ""
    NFS_HOSTNAME: ""
    RSTUDIO_AUTH_CLIENT_DOMAIN: ""
    RSTUDIO_AUTH_CLIENT_ID: ""
    RSTUDIO_AUTH_CLIENT_SECRET: ""
    JUPYTER_LAB_AUTH_CLIENT_DOMAIN: ""
    JUPYTER_LAB_AUTH_CLIENT_ID: ""
    JUPYTER_LAB_AUTH_CLIENT_SECRET: ""
    TOOLS_DOMAIN: ""
    ELASTICSEARCH_HOST: ""
    ELASTICSEARCH_PORT: ""
    ELASTICSEARCH_USERNAME: ""
    ELASTICSEARCH_PASSWORD: ""
  RDSPassword: ""
AWS:
  DefaultRegion: "eu-west-1"
  IAMRole: ""
tags:
  branch: false

ingress:
  addTlsBlock: true

postgresql:
    postgresHost: ""
    postgresUser: ""
    postgresPassword: ""
    postgresDatabase: ""
