ServicesDomain: ""
API:
  DeployOwnDatabase: false
  Branch: "api"
  Image:
    Repository: quay.io/mojanalytics/control-panel
    Tag: 0.1.0
    PullPolicy: IfNotPresent
  Environment:
    DEBUG: "False"
    ENV: ""
    IAM_ARN_BASE: ""
    K8S_WORKER_ROLE_NAME: ""
    LOGS_BUCKET_NAME: ""
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
    OIDC_DOMAIN: ""
    SAML_PROVIDER: ""
    SENTRY_DSN: ""
  RDSPassword: ""
AWS:
  DefaultRegion: "eu-west-1"
  IAMRole: ""
tags:
  branch: false

postgresql:
    postgresHost: ""
    postgresUser: ""
    postgresPassword: ""
    postgresDatabase: ""
