apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
    component: "webserver"
spec:
  sessionAffinity: ClientIP
  selector:
    app: {{ .Release.Name }}
    component: "webserver"
  ports:
    - port: 80
      targetPort: {{ .Values.authProxy.containerPort }}
