apiVersion: v1
entries:
  calicoctl:
  - appVersion: v1
    created: 2017-10-17T12:54:49.588249069Z
    description: calicoctl command line tool for configuring calico network provider
    digest: 13db458de9cad647ba0df9adeb1988e8ae8fcd974e69107eab58b96545f8ca6f
    name: calicoctl
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/calicoctl-0.1.0.tgz
    version: 0.1.0
  config-user:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.588515664Z
    description: Configure the user (e.g. git setup, etc...)
    digest: e484c230be1c06b39fe2b4e205abcb47e3d1344e551ddb8db1e6de19dae369a6
    name: config-user
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/config-user-0.1.0.tgz
    version: 0.1.0
  cpanel:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.593152899Z
    description: Analytics Platform Control Panel API webapp
    digest: 33e3d48acb4e7839cef606398fbd5390886131693bb27af940f17da68a0248e2
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.592283038Z
    description: Analytics Platform Control Panel API webapp
    digest: 3ac7f4b0d1d786deeba2b44dec8c7684267f0c4f029b63764a7ef8e2bf077b0c
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.590875285Z
    description: Analytics Platform Control Panel API webapp
    digest: addb70403be5a762a3cd6dc6863b4fa393b828952a597af8293d157d66268c6c
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.589907772Z
    description: Analytics Platform Control Panel API webapp
    digest: c5ebe6a774e2049c253451b1e082a09348ae17a23e94057961ccda5b69333a07
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.589641954Z
    description: Analytics Platform Control Panel API webapp
    digest: a6cbfd60946b7e8976054bb2c503cc53aee2bb381a8f5d2a914f002931fbd8fc
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.589362562Z
    description: Analytics Platform Control Panel API webapp
    digest: 905cac89f0e49e551612662ce4b88361c6e8c79cb6efacf0df93fff41b22fc31
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.589099327Z
    description: Analytics Platform Control Panel API webapp
    digest: f0600ee80bfe61cc1f666e7d81d67a2e1861b6d392b6843c492998e7c0157f32
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.588801136Z
    description: Analytics Platform Control Panel API webapp
    digest: 7895fbd7b317551cd5f795346d1b7094a966e6f0f426843d6a52bc3ee203b4dc
    name: cpanel
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpanel-0.1.0.tgz
    version: 0.1.0
  cpfrontend:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.593411591Z
    description: Analytics Platform Control Panel webapp
    digest: 30d04a056b3719332b425f8f049636d738dd412563ea6ccf8bd0b793c34ed701
    name: cpfrontend
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/cpfrontend-0.1.0.tgz
    version: 0.1.0
  elasticsearch-curator:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.593978677Z
    deprecated: true
    description: A Helm chart for Kubernetes
    digest: 5b6422aa20eb331e85c654b55d3f52660eb88e65d6c01bdb821067c5b6e22204
    name: elasticsearch-curator
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/elasticsearch-curator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.59368683Z
    description: A Helm chart for Kubernetes
    digest: 54e5490ccff6ce64369e0b74b9f7b7b8700ad88d3e8e22ac75b09253b13399f8
    name: elasticsearch-curator
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/elasticsearch-curator-0.1.0.tgz
    version: 0.1.0
  fluentd:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.594302916Z
    description: A Helm chart for Kubernetes
    digest: 8e018e33fc86d97aa991098abe1fa97687c07646b43abb04d4d0dd545e528c21
    name: fluentd
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/fluentd-0.1.0.tgz
    version: 0.1.0
  init-platform:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.594537976Z
    description: A Helm chart for Kubernetes
    digest: af7f2b2e3d14474542b54782bdf6d013150900fcc4750bda9d20f890f19dcc92
    name: init-platform
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/init-platform-0.1.0.tgz
    version: 0.1.0
  init-user:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.594800039Z
    description: A Helm chart for Kubernetes
    digest: ed07b6706f272ed5fbe72e33ca44921f7aecf30779b223d2da8aeac7678b128e
    name: init-user
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/init-user-0.1.0.tgz
    version: 0.1.0
  kibana-auth-proxy:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.59540475Z
    description: A Helm chart for Kubernetes
    digest: dcdb6cff1d5208c81cbddf66c4a035b360876025484b984ec9d5a467551e695e
    name: kibana-auth-proxy
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kibana-auth-proxy-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.59512709Z
    description: A Helm chart for Kubernetes
    digest: 20cf78f9638fb0f5bffa58304d55fa4cce02c7518349c50643ce88d62b89dc81
    name: kibana-auth-proxy
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kibana-auth-proxy-0.1.0.tgz
    version: 0.1.0
  kube-dashboard:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.595706663Z
    description: A Helm chart for Kubernetes
    digest: 2d82880a250c8088ab368e43e966c95533d6ac0839a1e9443f3756bb5893bd62
    name: kube-dashboard
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube-dashboard-0.1.0.tgz
    version: 0.1.0
  kube2iam:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.596172144Z
    description: Allows k8s pods to be started with AWS IAM roles attached
    digest: e03e67fbf416b5f68c36267ee73c008f18e3f31d23b9cdf652807cc6bc49bf80
    name: kube2iam
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube2iam-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.595934053Z
    description: Allows k8s pods to be started with AWS IAM roles attached
    digest: 389f30b188fdacedddad1868aa40eb444a359fbaec912db5c9a29c6445071bcd
    name: kube2iam
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube2iam-0.1.0.tgz
    version: 0.1.0
  nfs-backup:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.596745985Z
    description: A Helm chart for Kubernetes
    digest: fc258c527551a2738a58e5211a6a7b0cbf4af331e255401e9b1c316655e074f0
    name: nfs-backup
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nfs-backup-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: 2017-10-17T12:54:49.596461192Z
    description: A Helm chart for Kubernetes
    digest: f6e09751b8326531a761af8459c1f7cb13f57aeea75f730c51a62520bbbbd3b4
    name: nfs-backup
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nfs-backup-0.1.1.tgz
    version: 0.1.1
  nfs-migration:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.597295706Z
    deprecated: true
    description: A Helm chart for Kubernetes
    digest: 945a2d60d842080f7b91c9256e84a04738487d4fbb36d31b50e4b5263cfd9cb2
    name: nfs-migration
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nfs-migration-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.597019819Z
    description: A Helm chart for Kubernetes
    digest: 02f63fac4170197cbe64221de23c1f0c578057bcf0804f5cd9afc4ed8860772c
    name: nfs-migration
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nfs-migration-0.1.0.tgz
    version: 0.1.0
  nginx-ingress:
  - created: 2017-10-17T12:54:49.598152835Z
    description: An nginx Ingress controller that uses ConfigMap to store the nginx
      configuration.
    digest: e3fb68576a309ef9d044de966fa8adaa0d9664f791d84bb1c3072360ad43d26b
    engine: gotpl
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    maintainers:
    - email: jack.zampolin@gmail.com
      name: Jack Zampolin
    - email: mgoodness@gmail.com
      name: Michael Goodness
    name: nginx-ingress
    sources:
    - https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nginx-ingress-0.3.0.tgz
    version: 0.3.0
  node-exporter:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.598416284Z
    description: A Helm chart for Kubernetes
    digest: 753964efaf9f3ac2e7bdb7c2065362ca38d685b8b9ff183a3ca8b0d9c14a9027
    name: node-exporter
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/node-exporter-0.1.0.tgz
    version: 0.1.0
  rstudio:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.601998432Z
    description: RStudio with Auth0 authentication proxy
    digest: f334ab6a51848f0b1329a332f87a3e071e834a97a6c0a3bfe80dfaca4f0371c4
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.2.4.tgz
    version: 1.2.4
  - apiVersion: v1
    created: 2017-10-17T12:54:49.601670661Z
    description: RStudio with Auth0 authentication proxy
    digest: 72da24950f3fb49e73a8220c46eb43a14a571b014f9d3b186b3ff30991d4a0ce
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.2.3.tgz
    version: 1.2.3
  - apiVersion: v1
    created: 2017-10-17T12:54:49.601351935Z
    description: RStudio with Auth0 authentication proxy
    digest: 1448fbe889d534514199e6d8cb8bb96ca420097475fee89573f983b66e62621e
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v1
    created: 2017-10-17T12:54:49.60103296Z
    description: RStudio with Auth0 authentication proxy
    digest: eef4d753d2edb6b8322bd42ecc848a2d79172acce14b06b9d07ffa1ed8cccb28
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.600705456Z
    description: RStudio with Auth0 authentication proxy
    digest: c5c8566f620682ac0b789f0f5fa705a37ceefba73fcc483f4d666f8628ca62bd
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.600343404Z
    description: A Helm chart for RStudio
    digest: 064a104466406eee87a8e0854dc4ea50aa2ad0d8c752ac8d1465d6eb7fff6d78
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.599982459Z
    description: A Helm chart for RStudio
    digest: 64a3ac54289a10bb0a3ee7773d5b9dfbb870f6034f341821f2753a17b6d9f04d
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    created: 2017-10-17T12:54:49.599588894Z
    description: A Helm chart for RStudio
    digest: a88b4e9241a012dd81062856dc27b78fa0fa107c80fdef2baedf7a635ea96233
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.599196884Z
    description: A Helm chart for RStudio
    digest: a2df2dfe7aa0d04a6d7de175b134cc2e1e3e1b930f8b2acfdbda52fb396a4329
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.598788518Z
    description: A Helm chart for RStudio
    digest: f55bd974609c8e7caded4af18170ebf7b8221effacec0a5724f593d4822f0f8b
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-0.2.2.tgz
    version: 0.2.2
  shiny-app:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.602748026Z
    deprecated: true
    description: Shiny app Helm chart for Kubernetes
    digest: 1ad76530ca1d5c2cbedb21880e3790fd11d6d9a7282c1beae206d2524e24375a
    name: shiny-app
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/shiny-app-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.60236698Z
    description: Shiny app Helm chart for Kubernetes
    digest: f0d8293712dd5680b98bf586c8f1a02b56ffbfc859a60cbb93547ea9e97499f4
    name: shiny-app
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/shiny-app-0.1.0.tgz
    version: 0.1.0
  webapp:
  - apiVersion: v1
    created: 2017-10-17T12:54:49.605833594Z
    description: webapp Helm chart for Kubernetes
    digest: 7d94f6e386b963883dd6d4276330eba2b555b6bbd6e56eb59de53d55d2dd3c1e
    name: webapp
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/webapp-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.605429457Z
    description: webapp Helm chart for Kubernetes
    digest: 5ea408157135b6213d6e20f413aeb61797a6df02ccffbbc7cd43874b4ac90293
    name: webapp
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/webapp-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.604999583Z
    description: webapp Helm chart for Kubernetes
    digest: a5b415fdcd9bb839367141304bb77f1d8c9da13b74782d328d93afb58688000f
    name: webapp
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/webapp-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v1
    created: 2017-10-17T12:54:49.604562471Z
    description: webapp Helm chart for Kubernetes
    digest: f7df53771cee6e33fdeed01b83a0f3ab8d7ad9aff906e3983ddd8728f4dd80aa
    name: webapp
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/webapp-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v1
    created: 2017-10-17T12:54:49.603181557Z
    description: webapp Helm chart for Kubernetes
    digest: b67c59fb7afa3bb49124bbdc89e8554476c3e456ffd878b89a4091bc51041f4a
    name: webapp
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/webapp-1.0.0.tgz
    version: 1.0.0
generated: 2017-10-17T12:54:49.587864828Z
