# Docker image
image:
  name: quay.io/mojanalytics/go-unidler
  tag: v1.0.4
  pullPolicy: IfNotPresent

unidleKeyLabel: "host"

replicaCount: 3

service:
  externalPort: 80
  internalPort: 8080
  type: ClusterIP
