apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
  labels:
    app: cert-manager
    chart: {{ template "cert-manager-resources.chart" . }}
spec:
  acme:
    server: {{ .Values.issuer.acme.server }}
    email: {{ .Values.issuer.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}
    # ACME DNS-01 provider configurations
    dns01:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:
        - name: {{ .Values.issuer.dns01.provider.name }}
          route53:
            region: {{ .Values.issuer.dns01.provider.route53.region }}
            hostedZoneID: {{ .Values.issuer.dns01.provider.route53.hostedzoneid }}
