apiVersion: v1
appVersion: 1.13.8
description: Scales worker nodes within autoscaling groups
name: cluster-autoscaler
version: 0.1.5
sources:
- https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
- https://github.com/spotinst/kubernetes-autoscaler/tree/master/cluster-autoscaler
