apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ include "host" . | trunc 63 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ template "host" . }}
    http:
      paths:
      - backend:
          serviceName: "{{ .Chart.Name }}"
          servicePort: 80
  - host: {{ template "old_host" . }}
    http:
      paths:
      - backend:
          serviceName: "{{ .Chart.Name }}"
          servicePort: 80
  - host: {{ template "old_cpfrontend_host" . }}
    http:
      paths:
      - backend:
          serviceName: "{{ .Chart.Name }}"
          servicePort: 80
  tls:
  - hosts:
    - {{ template "host" . }}
    - {{ template "old_host" . }}
