apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migration"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: django-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h $DB_HOST; do
                sleep 2
              done
              python3 manage.py migrate
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-db-env"
      restartPolicy: OnFailure
  backoffLimit: 5
