apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Chart.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.API.Environment.OIDC_CLIENT_ID | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.API.Environment.OIDC_CLIENT_SECRET | b64enc | quote }}
  OIDC_DOMAIN: {{ .Values.API.Environment.OIDC_DOMAIN | b64enc | quote }}
  OIDC_AUTH_EXTENSION_URL: {{ .Values.API.Environment.OIDC_AUTH_EXTENSION_URL | b64enc | quote }}
  SENTRY_DSN: {{ .Values.API.Environment.SENTRY_DSN | b64enc | quote }}
  NFS_HOSTNAME: {{ .Values.API.Environment.NFS_HOSTNAME | b64enc | quote }}
  TOOLS_DOMAIN: {{ .Values.API.Environment.TOOLS_DOMAIN | b64enc | quote }}
  RSTUDIO_AUTH_CLIENT_DOMAIN: {{ .Values.API.Environment.RSTUDIO_AUTH_CLIENT_DOMAIN | b64enc | quote }}
  RSTUDIO_AUTH_CLIENT_ID: {{ .Values.API.Environment.RSTUDIO_AUTH_CLIENT_ID | b64enc | quote }}
  RSTUDIO_AUTH_CLIENT_SECRET: {{ .Values.API.Environment.RSTUDIO_AUTH_CLIENT_SECRET | b64enc | quote }}
  JUPYTER_LAB_AUTH_CLIENT_DOMAIN: {{ .Values.API.Environment.JUPYTER_LAB_AUTH_CLIENT_DOMAIN | b64enc | quote }}
  JUPYTER_LAB_AUTH_CLIENT_ID: {{ .Values.API.Environment.JUPYTER_LAB_AUTH_CLIENT_ID | b64enc | quote }}
  JUPYTER_LAB_AUTH_CLIENT_SECRET: {{ .Values.API.Environment.JUPYTER_LAB_AUTH_CLIENT_SECRET | b64enc | quote }}
  ELASTICSEARCH_HOST: {{ .Values.API.Environment.ELASTICSEARCH_HOST | b64enc | quote }}
  ELASTICSEARCH_USERNAME: {{ .Values.API.Environment.ELASTICSEARCH_USERNAME | b64enc | quote }}
  ELASTICSEARCH_PASSWORD: {{ .Values.API.Environment.ELASTICSEARCH_PASSWORD | b64enc | quote }}
