Username: ""
EnvName: "test"
CookieSecret: ""
WebApp:
  Name: ""
  BaseHost: ""
  ReplicaCount: 3
  GithubRepo: ""
  Port: 80
  Image:
    Repository: ""
    Tag: ":latest"
    PullPolicy: Always
AuthProxy:
  AuthenticationRequired: "true"
  IPRanges: ""
  Auth0:
    ClientSecret: ""
    ClientId: ""
    Domain: "AUTH0_USER.eu.auth0.com"
  Image:
    Repository: quay.io/mojanalytics/auth-proxy
    Tag: "v4.0.1"
    PullPolicy: "IfNotPresent"
AWS:
  IAMRole: ""
FluentBit:
  LogLevel: "info"
  # https://hub.docker.com/r/fluent/fluent-bit
  Image:
    Repository: fluent/fluent-bit
    Tag: 1.1.1 # Add `-debug` for debugging image
    PullPolicy: "IfNotPresent"
  Resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 1m
      memory: 1Mi
Elasticsearch:
  Scheme: "http"
  Host: ""
  Port: "9200"
  Username: ""
  Password: ""
