Username: ""
EnvName: "test"
CookieSecret: ""
WebApp:
  Name: ""
  BaseHost: ""
  ReplicaCount: 3
  GithubRepo: ""
  Port: 80
  Image:
    Repository: ""
    Tag: ":latest"
    PullPolicy: Always
AuthProxy:
  AuthenticationRequired: "true"
  IPRanges: ""
  Auth0:
    ClientSecret: ""
    ClientId: ""
    Domain: "AUTH0_USER.eu.auth0.com"
  Image:
    Repository: quay.io/mojanalytics/auth-proxy
    Tag: "v0.1.2"
    PullPolicy: "IfNotPresent"
AWS:
  IAMRole: ""
Fluentd:
  Image:
    Repository: quay.io/mojanalytics/fluentd
    Tag: tempFork
    PullPolicy: "IfNotPresent"
Elasticsearch:
  Scheme: "http"
  Host: ""
  Port: "9200"
  Username: ""
  Password: ""
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
