Username: ""
EnvName: "test"
ToolsDomain: "tools.EXAMPLE.COM"
CookieSecret: ""
WebApp:
  Name: ""
  BaseHost: ""
  ReplicaCount: 3
  GithubRepo: ""
  Port: 80
  Image:
    Repository: ""
    Tag: ":latest"
    PullPolicy: Always
AuthProxy:
  AuthenticationRequired: "true"
  IPRanges: ""
  Auth0:
    ClientSecret: ""
    ClientId: ""
    Domain: "AUTH0_USER.eu.auth0.com"
  Image:
    Repository: quay.io/mojanalytics/auth-proxy
    Tag: "v0.1.2"
    PullPolicy: "IfNotPresent"
AWS:
  IAMRole: ""
  AccessKeyId: ""
  SecretAccessKey: ""
  DefaultRegion: "eu-west-1"
Fluentd:
  Image:
    Repository: fluent/fluentd-kubernetes-daemonset
    Tag: stable-elasticsearch
    PullPolicy: "IfNotPresent"
Elasticsearch:
  Scheme: "http"
  Host: ""
  Port: "9200"
  Username: ""
  Password: ""
