apiVersion: v1
kind: Secret
metadata:
  name: fly
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  password: {{ .Values.concourse.password | b64enc | quote }}
  username: {{ .Values.concourse.username | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  auth0-authz-audience: {{ .Values.auth0.authzAudience | b64enc | quote }}
  auth0-authz-url: {{ .Values.auth0.authzUrl | b64enc | quote }}
  auth0-client-id: {{ .Values.auth0.clientId | b64enc | quote }}
  auth0-client-secret: {{ .Values.auth0.clientSecret | b64enc | quote }}
  auth0-domain: {{ .Values.auth0.domain | b64enc | quote }}
  gitcrypt-symmetric-key: {{ .Values.gitcryptSymmetricKey | b64enc | quote }}
  github-access-token: {{ .Values.github.accessToken | b64enc | quote }}
  github-webhook-token: {{ .Values.github.webhookToken | b64enc | quote }}
  kubernetes-api-url: {{ .Values.kubernetes.apiUrl | b64enc | quote }}
  kubernetes-ca-cert: {{ .Values.kubernetes.caCert | b64enc | quote }}
  kubernetes-token: {{ .Values.kubernetes.token | b64enc | quote }}
  quay-username: {{ .Values.quay.username | b64enc | quote }}
  quay-password: {{ .Values.quay.password | b64enc | quote }}
  services-domain: {{ .Values.servicesDomain | b64enc | quote }}
