apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
    host: {{ template "host" . }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-job
      labels:
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        host: {{ template "host" . }}
        # NOTE: DO NOT add `app` label here as it's used by the service
        #       to direct traffic to the jupyter pod and we don't want the
        #       Job's pod to receive that traffic.
    spec:
      serviceAccountName: {{ .Values.Username }}-jupyter
      restartPolicy: Never
      containers:
        - name: {{ template "fullname" . }}-bash-profile-config
          image: busybox
          command: [ "/bin/sh" ]
          args:
            - /{{ template "fullname" . }}/pip-user-home.sh
          volumeMounts:
            - name: nfs-home
              mountPath: /root
            - name: {{ template "fullname" . }}
              mountPath: /{{ template "fullname" . }}
      volumes:
        - name: nfs-home
          persistentVolumeClaim:
            claimName: nfs-home
        - name: {{ template "fullname" . }}
          configMap:
            name: {{ template "fullname" . }}
            defaultMode: 500
