apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  app-domain: {{ .Values.appDomain | b64enc | quote }}
  auth0-authz-audience: {{ .Values.auth0.authzAudience | b64enc | quote }}
  auth0-authz-url: {{ .Values.auth0.authzUrl | b64enc | quote }}
  auth0-client-id: {{ .Values.auth0.clientId | b64enc | quote }}
  auth0-client-secret: {{ .Values.auth0.clientSecret | b64enc | quote }}
  auth0-domain: {{ .Values.auth0.domain | b64enc | quote }}
  aws-region: {{ .Values.aws.region | b64enc | quote }}
  cookie-secret: {{ .Values.cookieSecret | b64enc | quote }}
  cpanel-api-url: {{ .Values.cpanelApiUrl | b64enc | quote }}
  ecr-access-key-id: {{ .Values.aws.ecrAccessKeyId | b64enc | quote }}
  ecr-secret-access-key: {{ .Values.aws.ecrSecretAccessKey | b64enc | quote }}
  github-access-token: {{ .Values.github.accessToken | b64enc | quote }}
  github-webhook-token: {{ .Values.github.webhookToken | b64enc | quote }}
  ip-102pf: {{ .Values.ipRanges.wifi102pf | b64enc | quote }}
  ip-dom1: {{ .Values.ipRanges.dom1 | b64enc | quote }}
  ip-quantum: {{ .Values.ipRanges.quantum | b64enc | quote }}
  kubernetes-api-url: {{ .Values.kubernetes.apiUrl | b64enc | quote }}
  kubernetes-ca-cert: {{ .Values.kubernetes.caCert | b64enc | quote }}
  kubernetes-token: {{ .Values.kubernetes.token | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: fly
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  password: {{ .Values.concourse.password | b64enc | quote }}
  username: {{ .Values.concourse.username | b64enc | quote }}
