{{- define "concourse-secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: concourse-{{ .team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  app-domain: {{ .Values.appDomain | b64enc | quote }}
  auth0-authz-audience: {{ .Values.auth0.authzAudience | b64enc | quote }}
  auth0-authz-url: {{ .Values.auth0.authzUrl | b64enc | quote }}
  auth0-client-id: {{ .Values.auth0.clientId | b64enc | quote }}
  auth0-client-secret: {{ .Values.auth0.clientSecret | b64enc | quote }}
  auth0-domain: {{ .Values.auth0.domain | b64enc | quote }}
  aws-region: {{ .Values.aws.region | b64enc | quote }}
  cookie-secret: {{ .Values.cookieSecret | b64enc | quote }}
  cpanel-api-password: {{ .Values.cpanelApi.password | b64enc | quote }}
  cpanel-api-url: {{ .Values.cpanelApi.url | b64enc | quote }}
  cpanel-api-user: {{ .Values.cpanelApi.user | b64enc | quote }}
  ecr-access-key-id: {{ .Values.aws.ecrAccessKeyId | b64enc | quote }}
  ecr-secret-access-key: {{ .Values.aws.ecrSecretAccessKey | b64enc | quote }}
  iam-list-roles-key-id: {{ .Values.aws.iamListRolesAccessKeyId | b64enc | quote }}
  iam-list-roles-secret-access-key: {{ .Values.aws.iamListRolesSecretAccessKey | b64enc | quote }}
  github-access-token: {{ .Values.github.accessToken | b64enc | quote }}
  github-webhook-token: {{ .Values.github.webhookToken | b64enc | quote }}
  ip-102pf: {{ .Values.ipRanges.wifi102pf | b64enc | quote }}
  ip-dom1: {{ .Values.ipRanges.dom1 | b64enc | quote }}
  ip-quantum: {{ .Values.ipRanges.quantum | b64enc | quote }}
  kubernetes-api-url: {{ .Values.kubernetes.apiUrl | b64enc | quote }}
  kubernetes-ca-cert: {{ .Values.kubernetes.caCert | b64enc | quote }}
  kubernetes-token: {{ .Values.kubernetes.token | b64enc | quote }}
  gitcrypt-symmetric-key: {{ .Values.gitCrypt.symmetricKey | b64enc | quote }}
  lookup-access-key-id: {{ .Values.aws.lookupAccessKeyId | b64enc | quote }}
  lookup-secret-access-key: {{ .Values.aws.lookupSecretAccessKey | b64enc | quote }}
  role-putter-access-key-id: {{ .Values.aws.rolePutterAccessKeyId | b64enc | quote }}
  role-putter-secret-access-key: {{ .Values.aws.rolePutterSecretAccessKey | b64enc | quote }}
  nodes-role-arn: {{ .Values.aws.nodesRoleArn | b64enc | quote }}
{{- end }}
---
{{ $_ := set . "team" .Values.concourse.target_team }}
{{ template "concourse-secrets" . }}
---
{{ $_ := set . "team" .Values.concourse.team }}
{{ template "concourse-secrets" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fly
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  password: {{ .Values.concourse.target_password | b64enc | quote }}
  username: {{ .Values.concourse.target_username | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: fly-admin
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  password: {{ .Values.concourse.password | b64enc | quote }}
  username: {{ .Values.concourse.username | b64enc | quote }}
